#For product service 
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:3242/mbanking_prod
    username: ${db_username}
    password: ITE2@2024
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
